### ISSUE TITLE
Add abstraction for web frameworks

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#147]
- [x] release node
- [x] create next js PR: https://github.com/vercel/next.js/pull/28916
- [x] Update website
- [x] Message on discord
- [x] https://app.zenhub.com/workspaces/supertokens-60df058bb63a6a0015cdd807/issues/supertokens/main-website/514
