### ISSUE TITLE
Tie email verification to sessions

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#164]
Right now, the frontend checks for email verification post login / sign up / on page reload. However, we want to tie email verification to a session so that we do not rely on the frontend to make this check (since it can be hacked to not make these checks).

So what I propose:
- Post login / sign up, we add info about email verification in the session.
- On every session verification, we check if the email is verified via the session jwt payload. If not (and the user wants email verification), we tell the frontend to redirect the user to the email verification screen.
- When redirected to the email verification screen, we check if the email is actually not verified. If it is, then we update the session, else we continue with the verification flow, and update the session post that. This will take care of cases where a user verifies an email on one session but others are still stale.
- On session refresh, we update if the email is verified

## TODO:
- [x] Updating a user's email should, by default mark them new email as unverified? If yes, then when that user accesses the web app next time and refreshes the session, it should take them to the email verification screen?
- [ ] Resolve https://github.com/supertokens/supertokens-auth-react/issues/278
- [ ] Resolve https://github.com/supertokens/supertokens-auth-react/issues/262
- [ ] https://github.com/supertokens/supertokens-node/issues/164#issuecomment-1015121795
- [ ]  On the frontend, we want to redirect to email verification screen (post sign up) only if a session exists. Cause there is a chance that a user might not want to create a new session post sign up and ask the user to login again. But what if the dev wants to finish email verification post sign up anyway and then ask the user to sign in again?

**Comment by rishabhpoddar** [comment]
We will need to modify the session recipe for this to begin with:
- The access token will contain an array of called "perm" (short for permissions), making the format of the access token as follows:
   ```
   {
      sessionHandle: "...",
      userId: "..",
      ....,
      userData: { /* custom nfo provided by user */}
      perm: [{
         id: "...", //  should be some globally unique string for this permission (perhaps the rid of the recipe)
         t: .... // time that this persmission was given or updated.
         ... // any other custom info, specific to this permission
      }, {...}]
   }
   ```
   Right now, we store only the `userData` in the db (used when creating a new access token during session refresh). We will have to change that to also store the `perm` array (ideally in a non breaking way). 

- Due to the above, one concern I have is that the size of the access token might become very large:
   - The access token is sent for every API call - resulting in sending more bytes per API call
   - The cookie size limit is 4k bytes per domain - what if we cross that? The size of our access tokens right now is 802 bytes without any custom user data and we will also be adding an optional JWT inside the access token so that people can use services like Hasura with a JWT. So this limit might start to become a real problem.

- The session recipe will need to expose the `perm` array on the frontend as well (which can be done via the `sFrontToken` token). And also expose a few functions to read / modify the contents of the perm array.  

- During session creation (in the login / sign up API), we let the emailverification recipe modify the perm array of that session based on if the email has been verified or not. If the email is not verified, there will be no entry for that in the `perm` array.

- The frontend / backend can then read the perm array to know if a user's email has been verified or not. If it has not been, and email verification is required (for all APIs / protected website routes), then:
   - For APIs: They will send a `403` error with a specific message that will indicate that email verification is required. The message format can be like:
      ```
      {
         status: "MISSING_PERM",
         perm: [{
            id: "..." // same as in the above code snippet
            ... // any other custom info, specific to this permission
         }, {...}]
      }
      ```
      On receiving this, a user of the supertokens-website SDK will need to show their email verification screen. A user of the auth-react SDK will be redirected to our email verification screen.

      We also need a way to say which APIs will care about this permission and which won't (even if they do session verification). For example, the API to generate an email verification link might need session verification, but would not return a `403` in case of missing perm for email verification.

      The `403` is something that will be sent by the session recipe and not the email verification recipe. Just like the try refresh token error, the user cannot override how this is sent to their frontend (unlike the unauthorised error).

      The refresh API will not need to check for any perm.
   - For website routes: We provide a function called `isEmailVerified` which now queries an API, but we can change that to check the contents of the access token. Furthermore, the email verification auth wrapper will check the access token as well.

- If a user has multiple sessions, and they verify their email in one session, that info is propagated to other sessions only if they are refreshed. So in those sessions, they might see the email verification screen. This issue can be solved by changing the APIs for email verification to first check if an email is verified, if yes, then update the existing session, and if not then continue with their existing logic. Furthermore, on the auth-react SDK, if the email verification screen is shown, that should query the backend to check if the email is actually verified or not (and not rely on the front token) before doing any operation or showing any UI.

- The `perm` feature should be made in a generic way that would suffice for 2fa as well. It should not be tied to email verification.

**Comment by rishabhpoddar** [comment]
As a side effect of this, I think that we can gid rid of all the recipe specific auth wrappers on the frontend and just have `SessionAuth` being used regardless of which recipes the user is using? Cause the only major diff between that and something like `EmailPasswordAuth` component is that `EmailPasswordAuth` also checks if the email is verified by an API call to the backend - which won't be needed anymore.
