### ISSUE TITLE
[Breaking change]: Return everything that is created during an api interface function & add a context object to all functions

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#215]
For example:
- the sign up / sign in api interfaces create a new session and a new user. Both should be returned.
- third party sign up / in also fetch the auth code response so we should return that as well (which we already do).

This is as per a new design principle that we have added.

-----------------
We should also add a context object to all functions (API, recipe and sending email functions) which can be freely modifed by the user to pass info across the functions.

These should also be added to the user facing function signatures, but should be optional there.

The should also be added to functions like `createAndSendCustomEmail` etc..

## TODO:
- [x] nodejs (usercontext-change branch)
   - [x] add context to social providers
- [x] golang
   - [x] userContext
   - [x] returning session for sign up / sign in
   - [x] testing
   - [x] session class changes
   - [x] Passing user context to session.revokeSession function in sign out API
   - [x] add context to social providers 
- [x] python
   - [x] userContext
   - [x] returning session for sign up / sign in
   - [x] testing
   - [x] session class changes
   - [x] Passing user context to session.revokeSession function in sign out API
   - [x] Expose regenerate session function to the user
   - [x] add context to social providers  
- [ ] supertokens-website
- [ ] supertokens-auth-react
- [ ] supertokens-react-native
- [x] Docs
   - [x] node
   - [x] golang
   - [x] python
   - [ ] website
   - [ ] auth react

**Comment by rishabhpoddar** [comment]
This is being done in auth-react and website in a separate issue already. So closing this.
