### ISSUE TITLE
Rework of thirdparty

### ISSUE THREAD

**Issue by sattvikc** [supertokens/supertokens-node#325]
1. Custom exchange of auth code
2. Function for get profile info - return all fields returned from provider
3. GetClientID without having to call Get on the provider, also for ClientSecret
4. Support for multi tenant - use function instead of static config (think if there are any better way to do it)
5. SignInUp does not have option to send any additional user data - one idea is to pass raw url instead of code
6. Add debug logs
7. Solve getRedirectURI issue
8. GET AuthorisationUrl API might need clientID
9. React SDK third party custom component redo. 
10. OpenID/Oauth Discovery endpoints

## TODO:
- [ ] core changes
   - [ ] write comment about list of APIs, their inputs / outputs and basic API logic and checks
   - [ ] impl changes in Java
- [ ] golang SDK
   - [ ] interface changes to thirdpartyemailpassword and thirdpartypasswordless recipe
   - [ ] backward compatibility
   - [ ] implementation of new recipe functions
   - [ ] tests
   - [ ] changelog and migration guide
   - [ ] Add connection URI and API key to BoxyHQ implementation
   - [ ] TenantID is optional, core will set it to public
   - [ ] should support multiple SAML, AD, okta providers
- [ ] web-js SDK
- [ ] auth-react SDK
    - [ ] Custom button should accept a name parameter - this is because the name comes from the backend, and when using custom UI, the custom UI must use the name from the backend.
    - [ ] Show button based on the third party id prefix
- [ ] nodejs SDK
- [ ] python SDK
- [ ] boiler plate code
- [ ] docs
   - [ ] website docs
   - [ ] section on getting user profile info
   - [ ] special case for apple - frontendRedirectURI and redirectURIOnProviderDashboard
   - [ ] user the multi-tenancy diagram and explain all the steps
   - [ ] CDI swagger
   - [ ] FDI swagger
   - [ ] add about dynamic CORS origin in multi tenant docs

**Comment by rishabhpoddar** [comment]
Related to:
- https://github.com/supertokens/supertokens-node/issues/295
- https://github.com/supertokens/supertokens-node/issues/218
- https://github.com/supertokens/supertokens-node/issues/298

**Comment by sattvikc** [comment]
Update API Spec for thirdparty

```
openapi: 3.0.1
info:
  title: Thirdparty
  description: Thirdparty
  version: 1.0.0
paths:
  /auth/authorisationrl:
    get:
      summary: Get Authorisation url
      operationId: authorisationUrlGET
      parameters:
      - name: thirdPartyId
        description: Thirdparty ID
        in: query
        required: true
        schema:
          type: string
      - name: clientId
        description: Thirdparty Provider ClientID
        in: query
        required: true
        schema:
          type: string
      - name: redirectURI
        description: Callback URI
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: Redirect URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
  /auth/signinup:
    post:
      summary: Sign In Up
      operationId: signInUpPOST
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SignInUpWithCode'
                - $ref: '#/components/schemas/SignInUpWithOAuthTokens'
      responses:
        200:
          description: Successful Sign In Up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInUpResult'
components:
  schemas:
    CodeChallenge:
      type: object
      properties:
        codeChallenge:
          type: string
          example: 123456abcdef
        codeChallengeMethod:
          type: string
          example: H256
    Url:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
        url:
          type: string
          example: https://oauth.com/authorise?...

        pkceCodeVerifier:
          type: string
          nullable: true

    SignInUpWithCode:
      type: object
      properties:
        thirdPartId:
          type: string
        clientID:
          type: string
        callbackInfo:
          type: object
          properties:
            redirectURI:
              type: string
            redirectURIQueryParams:
              type: object
              properties:
                code:
                  type: string
                state:
                  type: string
            pkceCodeVerifier:
              type: string
              nullable: true

    SignInUpWithOAuthTokens:
      type: object
      properties:
        thirdPartId:
          type: string
        clientID:
          type: string
        oAuthTokens:
          type: object
          example:
            access_token: "..."
            id_token: "..."
            "...": "..."
    SignInUpResult:
      type: object

```

**Comment by sattvikc** [comment]
# Thirdparty Rework

## Configuration

Configuration has been changed from adding multiple instances of the same provider with different configs to single instance of the provider with static list of configs.

Say you have multiple configurations for Google provider, you now create one provider instance that includes all the configs, instead of multiple instances of google.

```go
thirdparty.Init(tpmodels.TypeInput{
  SignInUpFeature: tpmodels.SignInUpFeature{
    Providers: []tpmodels.Providers{
      tpproviders.Google(tpmodels.TypeGoogleInput{
        Config: []tpmodels.GoogleConfig{
          {
            ClientID: "...", // For web
            ClientSecret: "...",
          },
          {
            ClientID: "...", // For mobile
            ClientSecret: "...",
          },
        }
      })
    }
  }
})
```

Internally, `findProvider` now just uses the thirdPartyId to match the provider and later the provider calls it's GetConfig method to get the appropriate config. If there is only single config specified in the config array, `clientID` would be optional on all the APIs and the config will be picked automatically. If there are multiple configs, `clientID` is required on all the APIs. If `clientID` is not specified or `clientID` is not found in the static list of configs, a runtime error will be thrown.

Based on the above logic, `IsDefault` has been removed from the config, and the right config is chosen based on `ThirdPartyId` and `ClientID`.

If you do not have a static list of config, you can override the `GetConfig` function to return the config dynamically.

```go
thirdparty.Init(tpmodels.TypeInput{
  SignInUpFeature: tpmodels.SignInUpFeature{
    Providers: []tpmodels.Providers{
      tpproviders.Google(tpmodels.TypeGoogleInput{
        Override: func(provider tpmodels.GoogleProvider) tpmodels.GoogleProvider {
          provider.GetConfig = func(clientID *string, userContext supertokens.UserContext) (tpmodels.GoogleConfig, error) {
            // Get the config from the database
            return tpmodels.GoogleConfig{
              ClientID: *clientID,
              ClientSecret: "...",
            }, nil
          }
          return provider
        }
      })
    }
  }
})
```

Overriding other functions in the GoogleProvider is also possible.

## Thirdparty provider interface

`Get` method has been removed from the Thirdparty Provider Interface and has been replaced with the following three methods, which would be sufficient to implement any thirdparty OAuth/OIDC based login flow.

PKCE flow is newly supported out of the box and as a general rule, skipping ClientSecret in the config would imply that the PKCE flow would be used.

If you wish to support both PKCE and ClientSecret flow for the same config, you can override the `ExchangeAuthCodeForOAuthTokens` method to support it. More details below.

### GetAuthorisationRedirectURL

`GetAuthorisationRedirectURL func(clientID *string, redirectURI string, userContext supertokens.UserContext) (TypeAuthorisationRedirect, error)`

This method is used to get fully formed authorisation URL for the provider which the frontend can redirect to.

In case of PKCE flow, `codeChallenge` and `codeChallengeMethod` are added in the url. `PKCECodeVerifier` is also provided, which the frontend will need to save and pass during the login completion.

### ExchangeAuthCodeForOAuthTokens

`ExchangeAuthCodeForOAuthTokens func(clientID *string, redirectInfo TypeRedirectURIInfo, userContext supertokens.UserContext) (TypeOAuthTokens, error)`

This method is responsible for exchanging AuthCode returned by the provider for OAuth tokens. This method accepts `redirectInfo` instead of just the code, which would contain all the queryParameters returned by the provider. This helps us capture additional info for providers like Apple, which also return logged in user's full name in the callback.

`redirectInfo` also contains optional `PKCECodeVerifier` if using the PKCE flow.

Note: For Apple, user info passed in the callbackQueryParams will be copied over to oAuthTokens in the default implementation.

### GetUserInfo

`GetUserInfo func(clientID *string, oAuthTokens TypeOAuthTokens, userContext supertokens.UserContext) (TypeUserInfo, error)`

This method is responsible for fetching user info using the `oAuthTokens` which would generally contain `access_token` and `id_token`. Along with `ThirdPartyUserId` and `EmailInfo`, this would also return `RawResponseFromProvider` which would contain all the data returned by the provider.

## Thirdparty API Interface changes

### AuthorisationRedirectUrlGET

- `clientID` is added as a query parameter, and is optional
- `redirectURI` is added as a query parameter, and is mandatory

This API will return a fully formed authorisation URL for the provider which the frontend can redirect to. Frontend will also append `state` to the url.

In case of PKCE, the returned URL will also contain `codeChallenge` and `codeChallengeMethod` as query parameters. `PKCECodeVerifier` is also provided, which the frontend will need to save and pass during the login completion.

### SignInUpPOST

- This API now accepts of the request body as metioned below:
- SignInUpWithCode
  - `clientID` is added to the request body, and is optional
  - `redirectURIInfo` is added to the request body, which would contain `redirectURI` and `redirectURIQueryParams` to include all the queryParams passed from the provider
  - `code` is removed
  - `pkceCodeVerifier` is an optional parameter, which is used in case of PKCE flow
- SignInUpWithOAuthTokens
  - `clientID` is added to the request body, and is optional
  - `oAuthTokens` is added to the request body, which would generally contain `access_token` and `id_token`. `oAuthTokens` also contains user info in case of Apple
- AppleRedirectHandlerPOST
  - Used for Apple provider only, to convert POST request on the backend to GET request on the frontend
  - `code` and `state` parameters have been removed and replaced with generic object `infoFromProvider` which would contain all the fields in the form and are converted to queryParams for the frontend url.

Reference API spec is in the previous comment.

**Comment by sattvikc** [comment]
Different Thirdparty flows

![image](https://user-images.githubusercontent.com/650429/183601626-5107e361-47d7-4992-ae1b-6a7d582c61ad.png)

**Comment by sattvikc** [comment]
Frontend will add frontend's redirect url to the state along with the random string for all providers. AppleRedirectHandlerPOST will use this frontend URL stored in the state to redirect from the backend. This would be useful in case of multi-tenancy handled by single backend domain as the frontend would have added originating login domain in the start of the flow.

**Comment by sattvikc** [comment]
**Notes:**

- GenerateCodeChallengePOST not required for web
- Backend determines the flow
- web frontend always generates codeChallenge and updates if authurlget returns codechallenge
- codechallenge is always passed to signinup & backend decides to use based on the flow
- if web and mobile uses different flow, override exchangecodefortokens function to support it.
- BackendRedirectHandler not required, keeping apple only

**TODO**

- [x]  check what’s preferred between FE PKCE Exchange on BE vs Backend PKCE
    - Backend PKCE is not commonly used as PKCE is meant for public auth more than private backend auth
- [ ]  For all providers, add frontend redirect url to state. Apple will consume it and redirect to frontend
- [ ]  change callbackURI to redirectURI

### State

- State is always generated and verified on frontend
- Backend will ignore state, if it is available in the callbackQueryParams

### PKCE

- Enabled/disabled in backend config
- For web, AuthoriseUrlGet also returns if PKCE is enabled
- For mobile
    - Option 1 - Add additional API In the backend to check if PKCE is enabled
        - Advantages
            - Uniform b/w web and mobile, backend informs about the flow
        - Disadvantages
            - Additional API call
    - Option 2 - Configure in the frontend (SDK)
        - Advantages
            - No additional API call
        - Disadvantages
            - More config on the frontend

### RedirectURI or CallbackURI

**CallbackURI only in frontend**

- Advantages
    - Backend will not deal with this and will always use value passed from frontend
    - Appropriate SDK will be able to send the right value and also provide option for overriding
- Disadvantages
    - In case of apple, callbackURI points to backend but still user needs to implement frontend route to handle it, which is confusing
    - More config on the frontend

**CallbackURI only in the backend**

- Option 1: Callback URI in the config
    - Advantages
        - Easy config for mobile
        - Can be overriden by overriding GetConfig function
    - Disadvantages
        - feels like it needs to be configured although it can be auto-generated
        - it cannot be auto generated for mobile
        - Overriding will be mandatory if same clientID is used between web and mobile
- Option 2: GetCallbackURI method in Provider
    - Advantages
        - One obvious place to override this
    - Disadvantages
        - Duplication of implementation
        - Cannot have default implementation for mobile
        - Overriding will be mandatory if same clientID is used between web and mobile

**Hybrid - Configure in backend, override from frontend (if necessary)**

- Advantages
    - Supports webflow easily by providing this value from backend
    - Supports mobile flow easily, as we pass this value to the SignInUp API
    - If mobile and web is using same client ID, mobile will override from the frontend to make this work seamlessly
    - Can be overridden in the backend as well by overriding the GetConfig function
- Disadvantages
    - Might be confusing that it is configured in backend and can only be overridden from frontend
    - Although configured, APIs will have this optional field
    - Duplication of implementation

- For web
    - AuthorisationUrlGET will provide this
    - Can be overriden using GetCallbackURI function on the backend
- For mobile
    - For frontend code exchange, Configured within the app & no changes on backend
    - For backend code exchange, Configured within the app & must override GetCallbackURIGET

**Special cases**

Apple

- Redirect URI points to backend by default.
- Provider implements BackendToFrontendRedirectHandler to convert POST request on the backend to GET request on the frontend. Apple’s implementation converts form fields to query parameters

## Implicit

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ac2e0328-2730-44f5-8832-68d5490ac003/Untitled.png)

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/22e8a717-5b71-4d9b-966b-7fc21e761bf7/Untitled.png)

- Not recommended, provides least security

**Comment by sattvikc** [comment]
26-10-2022

Frontend:

Interface changes:
```ts
ThirdParty.init({
  clientType?: "...", // "web", "ios", "android", etc.
  providers: [
    ...
  ],
  getTenantId?: () => Promise<String | null>,
})
```

Login buttons UI:
  - Call getTenantId() to get the tenant id
  - if tenant id is null
    - show the login buttons based on the provider array
  - else
    - call getProviders API to get the providers for the tenant
    - append entries from the providers array
      - for duplicate id, use the entry from the providers array
    - show the login buttons based on the updated list

Data needed for the login buttons UI:
  - id
  - name
  - button style | button component

---

Backend:

findProvider (thirdPartyId string, tenantId *string) => TypeProvider
  - if tenantId is null
    - return the provider with the given thirdPartyId from the provider array
  - else
    - query list of configs for (thirdPartyId, tenantId)
    - for each config in the list
      - if provider defined in provider array:
        - append the config to the provider
      - else
        - if provider is inbuilt, create inbuilt provider instance
        - else, create custom provider instance

getConfig (clientType?: string) => TypeConfig
  - if clientType is null
    - check clients array contains exactly one entry and return it
  - else
    - if clients array contains exactly one entry, return it
    - else, find matching matching clientType from the array and return it
  
  - throw error if no matching clientType found

GetUserPoolForTenant: (tenantId? string) => Promise<string>
  - default implementation: return tenantId
  - Note:
    - can return same value for different tenants if they wish to use a shared user pool

```ts
ProviderConfig: {
  clients: [{
		type?: "...", // "web", "ios", "android", etc.
		id: "...", // client id
		secret?: "...", // client secret
		scope: []
	}],
	authorisationEndpoint?: "...",
	authorisationEndpointQueryParams?: {...},
	tokenEndpoint?: "...",
	tokenParams?: {...},
	userInfoEndpoint?: "...",
	jwksUrl?: "...",
	oidcDiscoveryEndpoint?: "...",
	userInfoMap: {
    idField: "id",
    emailField: "email",
    emailVerifiedField: "email_verified",
  },
	validateIdTokenPayload?: async (idTokenPayload: {...}, clientConfig: {type?, id, secret?, scope, ... /* provider specific client config */}) => Promise<boolean>
}
```

fields in userInfoMap use dot notation to access nested fields: eg. "user.email"
emailVerified field considers boolean true or string "true" as true

optional `validateIdTokenPayload` is called after basic JWT verifications such as expiry, signature. It will be used for addition checks such as `hd === clientConfig.hd` for Google Workspaces.
  - idTokenPayload is the payload of the id token
  - clientConfig is the client config for the current client type

UserPool or TenantID as a separate column
   Pros:
    - UserID directly corresponds to thirdparty User ID and can be used without processing
    - Easy to query users by tenant id
  Cons:
    - Core upgrade is required
  Note:
    - Also need to store the tenant ids associated with the user

UserPool or TenantID as a prefix to userID
  Pros:
    - Core upgrade is not necessary
  Cons:
    - User ID needs to be preprocessed to get the thirdparty User ID and the UserPool
      - We can pre-process and expose them separately in the SDK
    - If a user pool corresponds to multiple tenants, tenantids cannot be stored as prefix

ThirdParty user:

```golang
type User struct {
	ID         string `json:"id"`
	TimeJoined uint64 `json:"timeJoined"`
	Email      string `json:"email"`
	ThirdParty struct {
		ID        string `json:"id"`
		UserID    string `json:"userId"`
    UserPool  string `json:"userPool"`
    TenantIds []string `json:"tenantIds"`
	} `json:"thirdParty"`
}
```

**Comment by sattvikc** [comment]
logic for GetProviderConfig:
- If tenantId === nil || tenantId === default
  - set tenantId = default
  - query db with this tenantId
  - merge static (remove all that have useForDefaultTenant as false) and db result keeping db as priority.
  - return merged result
- Else
  - query db with tenantId
  - If mapping not found, return static config
  - return db result

On the frontend:
- If fetchProvidersFromBackend is false (by default is true ):
  - return static list
- If tenantId === nil || tenantId === default
  - set tenantId = default
  - query API to get list of thirdpartyIds
  - merge static (remove all that have useForDefaultTenant as false) and API result keeping API as priority.
  - return merged result
- Else
  - query API with tenantId
  - If mapping not found, return static config
  - return API result

**Comment by sattvikc** [comment]
```
1. Create or update tenant config mapping

POST /recipe/thirdparty/tenant/config
Request:
{
  thirdPartyId: string;
  tenantId?: string;
  config: {
    clients: {
      clientType?: string;
      clientId: string;
      clientSecret: string;
      scope: string[];
      additionalConfig: {};
    }[];
    authorizationEndpoint?: string;
    authorizationEndpointQueryParams?: {};
    tokenEndpoint?: string;
    tokenEndpointBodyParams?: {};
    forcePKCE?: boolean;
    userInfoEndpoint?: string;
    userInfoEndpointQueryParams?: {};
    userInfoEndpointHeaders?: {};
    jwksURI?: string;
    oidcDiscoveryEndpoint?: string;
    userInfoMap?: {
      fromIdTokenPayload?: {
        userId?: string;
        email?: string;
        emailVerified?: string;
      },
      fromUserInfoAPI?: {
        userId?: string;
        email?: string;
        emailVerified?: string;
      };
    };
    name: string;
  }
}

Request validation:
- thirdPartyId is required
- if tenantId is null, it will be set to `defaultTenantId`
- clients array cannot be empty
- if clients array contains only 1 Element, clientType is optional
- if clients array contains more than 1 Element, clientType is required and must be unique

- checks on the additionalConfig based on the thirdPartyId for builtin providers
    apple:
      additionalConfig must contain 'keyId', 'teamId', 'privateKey'
    okta:
      additionalConfig must contain 'oktaDomain'
    active Directory:
      additionalConfig must contain 'directoryId'
    google Workspaces:
      additionalConfig may contain 'hd'
    discord:
      additionalConfig may contain 'requireEmail'

response:
{
  status: "OK";
  createdNew: boolean;
} |
{
  status: "VALIDATION_ERROR";
  message: string;
}

=====

2. Get tenant config mapping
GET /recipe/thirdparty/tenant/config

Request Query Params:
{
  thirdPartyId: string;
  tenantId?: string;
}

if tenantId is null, `defaultTenantId` to be used

Response:
{
  status: "OK";
  config: { ... same as above }
} |
{
  status: "UNKNOWN_MAPPING_ERROR"
}

=====

3. Remove Tenant config mapping
POST /recipe/thirdparty/tenant/config/remove
Request:
{
  thirdPartyId: string;
  tenantId?: string;
}

if tenantId is null, `defaultTenantId` to be used

Response:
{
  status: "OK";
  mappingExisted: boolean;
}

=====

4. List config mappings for tenant or thirdPartyId or all
GET /recipe/thirdparty/tenant/config/list
Request query params:
{
  id?: string;
  idType?: "THIRDPARTY_ID" | "TENANT_ID";
}

or

{
  thirdPartyId?: string;
  tenantId?: string;
}

If tenantId is null, `defaultTenantId` to be used

Response:
{
  status: "OK";
  configs: {
    thirdPartyId: string;
    tenantId: string;
    config: { ... same as above }
  }[];
}

if id == null && idType == null -> return all mappings
if id == null && idType == "THIRDPARTY_ID" -> Error
if id == null && idType == "TENANT_ID" -> return all mappings for the default tenant tenant
if id != null && idType == null -> Error
if id != null && idType == "THIRDPARTY_ID" -> return all mappings for the given thirdPartyId
if id != null && idType == "TENANT_ID" -> return all mappings for the given tenantId

Notes: needs pagination??

=====

5. List all tenants
GET /recipe/thirdparty/tenant/list

Response:
{
  status: "OK";
  tenantIds: string[];
}
```
